{% set name = "pytest-dependency" %}
{% set version = "0.5.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c2a892906192663f85030a6ab91304e508e546cddfe557d692d61ec57a1d946b

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -v --no-deps --no-build-dependency

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
    - setuptools_scm
  run:
    - pytest
    - python

test:
  imports:
    - pytest_dependency
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/RKrahl/pytest-dependency
  summary: Manage dependencies of tests
  description: |
    This pytest plugin manages dependencies of tests. 
    It allows to mark some tests as dependent from other tests. 
    These tests will then be skipped if any of the dependencies did fail or has been skipped.
  license: Apache-2.0
  license_file: LICENSE.txt
  license_family: Aparche
  dev_url: https://github.com/RKrahl/pytest-dependency
  doc_url: https://github.com/RKrahl/pytest-dependency

extra:
  recipe-maintainers:
    - Windiana42 
